site_favicon: favicon-96x96.png
#theme: minimal
#markdown: kramdown
description: Short summary.
highlighter: rouge
plugins:
    - jekyll-seo-tag
    # Build settings
remote_theme: jekyll/minima
<link rel="shortcut icon" type="image/x-icon" href="wt/favicon.ico">
