site_favicon: favicon.ico
#theme: minimal
markdown: kramdown
description: Short summary.
highlighter: rouge
kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: true
plugins:
    - jekyll-seo-tag
    # Build settings
remote_theme: jekyll/minima
